on:
  release:
    types: [created]

name: Builds and publishes a new release

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-18.04

    steps:
    - name: Add checkout
      uses: actions/checkout@v2
    
    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker build
      run: docker build $GITHUB_WORKSPACE --platform linux/amd64 --file $GITHUB_WORKSPACE/.github/workflows/Dockerfile --tag saiintbrisson/mine-proxy:$RELEASE_VERSION

    - name: Docker push
      run: docker push saiintbrisson/mine-proxy:$RELEASE_VERSION

    - name: Docker image digest
      run: echo ${{ steps.docker_build.outputs.digest }}